name: 'Build Docker image'

description: "Build a Docker image, specific to this repository's needs."

inputs:
    backend:
        description: >
            Kokkos-compatible backend.
        required: true
        type: string

    compiler_family:
        description: >
            Compiler family for... compiling.
        required: true
        type: choice
        options:
            - gcc
            - clang
            - rocm

    kokkos_arch:
        description: >
            Kokkos architecture to enable.
        required: false
        type: string

    base_image:
        description: >
            Docker base image to start from.
        required: true

    tag:
        description: >
            Tag of the resulting image.
        required: true
        type: string

    platforms:
        description: >
            Platforms (for multi-platform Docker builds).
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - shell: sh
          run  : |
            echo "CLANG_VERSION=$(jq '.dependencies.clang.value' version.json -j)" >> $GITHUB_ENV

            echo "CMAKE_VERSION=$(jq '.dependencies.cmake.value' version.json -j)" >> $GITHUB_ENV

            echo "DOXYGEN_VERSION=$(jq '.dependencies.doxygen.value' version.json -j)" >> $GITHUB_ENV

            echo "GOOGLETEST_VERSION=$(jq '.dependencies.googletest.value' version.json -j)" >> $GITHUB_ENV

            echo "HPX_REF=v$(jq '.dependencies.hpx.value' version.json -j)" >> $GITHUB_ENV

            echo "KOKKOS_BRANCH=$(jq '.dependencies.kokkos.branch' version.json -j)" >> $GITHUB_ENV
            echo "KOKKOS_SHA=$(   jq '.dependencies.kokkos.sha'    version.json -j)" >> $GITHUB_ENV
            echo "KOKKOS_URL=$(   jq '.dependencies.kokkos.url'    version.json -j)" >> $GITHUB_ENV

            echo "KOKKOS_KERNELS_BRANCH=$(jq '.dependencies."kokkos-kernels".branch' version.json -j)" >> $GITHUB_ENV
            echo "KOKKOS_KERNELS_SHA=$(   jq '.dependencies."kokkos-kernels".branch' version.json -j)" >> $GITHUB_ENV

            echo "KOKKOS_UTILS_BRANCH=$(jq '.dependencies."kokkos-utils".branch' version.json -j)" >> $GITHUB_ENV
            echo "KOKKOS_UTILS_SHA=$(   jq '.dependencies."kokkos-utils".sha'    version.json -j)" >> $GITHUB_ENV

            echo "NVIDIA_STDEXEC_REF=$(jq '.dependencies.nvidia.stdexec.value' version.json -j)" >> $GITHUB_ENV

        - uses: docker/setup-buildx-action@v3

        - uses: docker/build-push-action@v6.13.0
          with:
              context: .
              platforms: ${{ inputs.platforms }}
              push: ${{ github.ref == 'refs/heads/main' }}
              file: docker/dockerfile
              tags: ${{ inputs.tag }}
              cache-from: type=registry,ref=${{ inputs.tag }}
              cache-to: type=inline
              build-args: |
                  BASE_IMAGE=${{ inputs.base_image }}
                  CLANG_VERSION=${{ env.CLANG_VERSION }}
                  CMAKE_VERSION=${{ env.CMAKE_VERSION }}
                  COMPILER_FAMILY=${{ inputs.compiler_family }}
                  DOXYGEN_VERSION=${{ env.DOXYGEN_VERSION }}
                  GOOGLETEST_VERSION=${{ env.GOOGLETEST_VERSION }}
                  HPX_REF=${{ env.HPX_REF }}

                  KOKKOS_ARCH=${{ inputs.kokkos_arch }}
                  KOKKOS_BRANCH=${{ env.KOKKOS_BRANCH }}
                  KOKKOS_PRESET=${{ inputs.compiler_family }}-${{ inputs.backend }}
                  KOKKOS_SHA=${{ env.KOKKOS_SHA }}
                  KOKKOS_URL=${{ env.KOKKOS_URL }}

                  KOKKOS_KERNELS_BRANCH=${{ env.KOKKOS_KERNELS_BRANCH }}
                  KOKKOS_KERNELS_SHA=${{ env.KOKKOS_KERNELS_SHA }}

                  KOKKOS_UTILS_BRANCH=${{ env.KOKKOS_UTILS_BRANCH }}
                  KOKKOS_UTILS_SHA=${{ env.KOKKOS_UTILS_SHA }}

                  NVIDIA_STDEXEC_REF=${{ env.NVIDIA_STDEXEC_REF }}
              labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"
