function(kokkos_interface_compile_options_has_sycl_cuda_arch)
    get_target_property(COMPILE_OPTS Kokkos::kokkoscore INTERFACE_COMPILE_OPTIONS)

    string(FIND "${COMPILE_OPTS}" "-fsycl-targets=nvptx64-nvidia-cuda" KOKKOS_INTERFACE_COMPILE_OPTIONS_HAS_SYCL_CUDA_ARCH)
    if(KOKKOS_INTERFACE_COMPILE_OPTIONS_HAS_SYCL_CUDA_ARCH GREATER 0)
        set(KOKKOS_INTERFACE_COMPILE_OPTIONS_HAS_SYCL_CUDA_ARCH TRUE PARENT_SCOPE)
    else()
        set(KOKKOS_INTERFACE_COMPILE_OPTIONS_HAS_SYCL_CUDA_ARCH FALSE PARENT_SCOPE)
    endif()
endfunction()

function(sycl_ur_cuda_skip TARGET)
    if(SYCL IN_LIST Kokkos_DEVICES)
        if(CMAKE_CXX_COMPILER_ID STREQUAL IntelLLVM AND CMAKE_CXX_COMPILER_VERSION STREQUAL 2025.3.3)
            kokkos_interface_compile_options_has_sycl_cuda_arch()
            if(KOKKOS_INTERFACE_COMPILE_OPTIONS_HAS_SYCL_CUDA_ARCH)
                message(WARNING "Disabling ${TARGET} for SYCL because of issues with UR+CUDA.")
                set_tests_properties(${TARGET} PROPERTIES DISABLED TRUE)
            endif()
        endif()
    endif()
endfunction()
