ARG BASE_IMAGE

# Install Python3 (with the trickery for virtual environment).
FROM ${BASE_IMAGE} AS requirements

ARG PYTHON_VERSION=3.12
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git
    python3 -m venv $VIRTUAL_ENV
    apt clean && rm -rf /var/lib/apt/lists/*
EOF

ARG COMPILER_FAMILY
ARG TARGETARCH

# Install APT requirements and compiler.
RUN --mount=target=/requirements,type=bind,source=requirements <<EOF
    set -ex

    python3 -m pip install git+https://github.com/uliegecsm/system-helpers

    if [ "${COMPILER_FAMILY}" = "gcc" ];then
        COMPILER_FAMILY_REQUIREMENTS=g++
    elif [ "${COMPILER_FAMILY}" = "clang" ];then
        COMPILER_FAMILY_REQUIREMENTS="clang clang-tidy libomp-dev"
    elif [ "${COMPILER_FAMILY}" = "ROCm" ];then
        COMPILER_FAMILY_REQUIREMENTS=
    else
        echo "unsupported compiler family ${COMPILER_FAMILY}"
        exit -1
    fi

    apt-helpers install-packages --clean --update           \
        --packages ${COMPILER_FAMILY_REQUIREMENTS}          \
        --requirement /requirements/requirements.system.txt \
        --requirement /requirements/requirements.system.hpx.txt
EOF

ARG CMAKE_VERSION

RUN <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        SUFFIX=x86_64
    elif [ "${TARGETARCH}" = "arm64" ];then
        SUFFIX=aarch64
    else
        echo "unsupported target arch ${TARGETARCH}"
    fi

    INSTALLER=cmake-${CMAKE_VERSION}-linux-${SUFFIX}.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

# Compile Google Test.
FROM requirements AS google-test-compile

ARG GOOGLETEST_VERSION

RUN <<EOF
    set -ex

    git clone --depth=1 --branch=v${GOOGLETEST_VERSION} https://github.com/google/googletest googletest

    cd googletest

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install
EOF

# Fetch HPX sources, configure, build and install.
FROM requirements AS hpx-compile

ARG HPX_REF
ARG HPX_SOURCE_DIR=/opt/hpx-${HPX_REF}-sources/

RUN git clone --depth=1 --branch=${HPX_REF} -- https://github.com/STELLAR-GROUP/hpx.git ${HPX_SOURCE_DIR}

RUN --mount=target=/cmake/presets/hpx.json,type=bind,source=cmake/presets/hpx.json <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        ADDITIONAL_CONFIG_ARGS=
    elif [ "${TARGETARCH}" = "arm64" ];then
        # This option seems needed for ARM.
        # https://hpx-docs.stellar-group.org/latest/html/manual/building_hpx.html#cmdoption-arg-HPX_WITH_GENERIC_CONTEXT_COROUTINES
        ADDITIONAL_CONFIG_ARGS=-DHPX_WITH_GENERIC_CONTEXT_COROUTINES:BOOL=ON
    else
        echo "unsupported target arch ${TARGETARCH}"
        exit -1
    fi

    cd ${HPX_SOURCE_DIR}

    cp /cmake/presets/hpx.json CMakePresets.json

    cmake -S . --preset=${COMPILER_FAMILY} ${ADDITIONAL_CONFIG_ARGS}
    cmake --build --preset=${COMPILER_FAMILY} -j4
    cmake --install build-with-${COMPILER_FAMILY} --prefix=/opt/hpx-${HPX_REF}/
EOF

# Compile Kokkos.
FROM hpx-compile AS kokkos-compile

ARG KOKKOS_ARCH
ARG KOKKOS_BRANCH
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_VERSION

RUN git clone --shallow-since=2023-08-05 --branch=${KOKKOS_BRANCH} https://github.com/kokkos/kokkos /kokkos-sources

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json <<EOF
    set -ex

    cd /kokkos-sources

    git checkout ${KOKKOS_SHA}

    cp /cmake/presets/kokkos.json CMakePresets.json

    if [ -z "${KOKKOS_ARCH}" ];then
        echo "> No Kokkos architecture given."
    else
        search_str="REPL_STR_KOKKOS_ARCH_ENABLED"
        replace_str="Kokkos_ARCH_${KOKKOS_ARCH}"
        echo "> Replacing '${search_str}' by '${replace_str}'."
        sed -i -e 's/'${search_str}'/'${replace_str}'/g' CMakePresets.json
    fi

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target=install
EOF

# Compile Kokkos Tools.
# It seems that Kokkos from the previous stage will be detected, so we don't need a presets file.
FROM kokkos-compile AS kokkos-tools-compile

ARG KOKKOS_PRESET
ARG KOKKOS_TOOLS_BRANCH=develop
ARG KOKKOS_TOOLS_SHA=a9453b21e09c7555096f3a96bb3fa8b34afe19f8
ARG KOKKOS_VERSION

RUN git clone --shallow-since=2023-08-05 --branch=${KOKKOS_TOOLS_BRANCH} https://github.com/kokkos/kokkos-tools /kokkos-tools-sources

RUN --mount=target=/cmake/presets/kokkos-tools.json,type=bind,source=cmake/presets/kokkos-tools.json <<EOF
    set -ex

    cd /kokkos-tools-sources

    git checkout ${KOKKOS_TOOLS_SHA}

    cp /cmake/presets/kokkos-tools.json CMakePresets.json

    export Kokkos_ROOT=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-tools/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target=install
EOF

# Compile Doxygen.
FROM requirements AS doxygen-compile

ARG DOXYGEN_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages flex bison

    git clone --depth=1 --branch Release_$(echo ${DOXYGEN_VERSION} | tr . _) https://github.com/doxygen/doxygen doxygen

    cd doxygen

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Fetch https://github.com/NVIDIA/stdexec sources.
FROM requirements AS nvidia-stdexec

ARG NVIDIA_STDEXEC_REF

RUN <<EOF
    set -ex

    git clone --branch main --shallow-since=2024-06-01 https://github.com/NVIDIA/stdexec /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}

    cd /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}

    git checkout ${NVIDIA_STDEXEC_REF}
EOF

# Fetch https://github.com/SergiusTheBest/plog sources and install.
FROM requirements AS sergius-plog

ARG SERGIUS_PLOG_REF

RUN <<EOF
    set -ex

    git clone --branch master --shallow-since=2024-06-01 https://github.com/SergiusTheBest/plog /opt/sergius/plog-${SERGIUS_PLOG_REF}-sources

    cd /opt/sergius/plog-${SERGIUS_PLOG_REF}-sources

    git checkout ${SERGIUS_PLOG_REF}

    cmake -S . -B build \
        -DCMAKE_INSTALL_PREFIX=/opt/sergius/plog-${SERGIUS_PLOG_REF} \
        -DPLOG_BUILD_SAMPLES=OFF \
        -DPLOG_BUILD_TESTS=OFF

    cmake --build build -j4 --target install
EOF

# Build the final image from previous stages.
FROM requirements AS final

ARG DOXYGEN_VERSION
ARG GOOGLETEST_VERSION
ARG HPX_REF
ARG KOKKOS_VERSION
ARG KOKKOS_PRESET
ARG NVIDIA_STDEXEC_REF
ARG SERGIUS_PLOG_REF

COPY --from=doxygen-compile      /opt/doxygen-${DOXYGEN_VERSION}                /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-test-compile  /opt/google-test-${GOOGLETEST_VERSION}         /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=hpx-compile          /opt/hpx-${HPX_REF}                            /opt/hpx-${HPX_REF}
COPY --from=kokkos-compile       /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET} /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}
COPY --from=kokkos-tools-compile /opt/kokkos-tools/${KOKKOS_PRESET}             /opt/kokkos-tools/${KOKKOS_PRESET}
COPY --from=nvidia-stdexec       /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}      /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}
COPY --from=sergius-plog         /opt/sergius/plog-${SERGIUS_PLOG_REF}          /opt/sergius/plog-${SERGIUS_PLOG_REF}

ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV HPX_ROOT=/opt/hpx-${HPX_REF}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}
ENV plog_ROOT=/opt/sergius/plog-${SERGIUS_PLOG_REF}
ENV Stdexec_ROOT=/opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}
