ARG BASE_IMAGE

FROM ${BASE_IMAGE} AS requirements

ARG COMPILER_FAMILY

# Install APT requirements and compiler.
RUN --mount=target=/requirements,type=bind,source=requirements <<EOF

    set -ex

    apt update

    if [ "${COMPILER_FAMILY}" = "gcc" ];then
        COMPILER_FAMILY_REQUIREMENTS=g++
    elif [ "${COMPILER_FAMILY}" = "clang" ];then
        COMPILER_FAMILY_REQUIREMENTS="clang libomp-dev"
    else
        echo "unsupported compiler family ${COMPILER_FAMILY}"
        exit -1
    fi

    apt --yes --no-install-recommends install ${COMPILER_FAMILY_REQUIREMENTS}

    apt --yes --no-install-recommends install $(grep -vE "^\s*#" /requirements/requirements.system.txt     | tr "\n" " ")
    apt --yes --no-install-recommends install $(grep -vE "^\s*#" /requirements/requirements.system.hpx.txt | tr "\n" " ")

    apt clean && rm -rf /var/lib/apt/lists/*

EOF

ARG CMAKE_VERSION

RUN <<EOF

    INSTALLER=cmake-${CMAKE_VERSION}-linux-x86_64.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

# Compile Google Test.
FROM requirements AS google-test-compile

ARG GOOGLETEST_VERSION

RUN <<EOF

    set -ex

    git clone --depth=1 --branch=v${GOOGLETEST_VERSION} https://github.com/google/googletest googletest

    cd googletest

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install

EOF

# Fetch HPX sources, configure, build and install.
FROM requirements AS hpx-compile

ARG HPX_REF
ARG HPX_SOURCE_DIR=/opt/hpx-${HPX_REF}-sources/

RUN git clone --depth=1 --branch=${HPX_REF} -- https://github.com/STELLAR-GROUP/hpx.git ${HPX_SOURCE_DIR}

RUN --mount=target=/cmake/presets/hpx.json,type=bind,source=cmake/presets/hpx.json <<EOF

    set -ex

    cd ${HPX_SOURCE_DIR}

    cp /cmake/presets/hpx.json CMakePresets.json

    cmake -S . --preset=${COMPILER_FAMILY}
    cmake --build --preset=${COMPILER_FAMILY} -j4
    cmake --install build-with-${COMPILER_FAMILY} --prefix=/opt/hpx-${HPX_REF}/
EOF

# Compile Kokkos.
FROM hpx-compile AS kokkos-compile

ARG KOKKOS_GIT_REF
ARG KOKKOS_PRESET
ARG KOKKOS_VERSION

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json <<EOF

    set -ex

    git clone --depth=1 --branch=${KOKKOS_GIT_REF} https://github.com/kokkos/kokkos kokkos

    cd kokkos

    cp /cmake/presets/kokkos.json CMakePresets.json

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4

    cmake --build --preset=${KOKKOS_PRESET} --target=install

EOF

# Compile Doxygen.
FROM requirements AS doxygen-compile

ARG DOXYGEN_VERSION

RUN <<EOF

    set -ex

    apt update

    apt --yes --no-install-recommends install flex bison python3

    git clone --depth=1 --branch Release_$(echo ${DOXYGEN_VERSION} | tr . _) https://github.com/doxygen/doxygen doxygen

    cd doxygen

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4

    cmake --build build --target install

    apt clean && rm -rf /var/lib/apt/lists/*

EOF

# Fetch https://github.com/NVIDIA/stdexec sources.
FROM requirements AS nvidia-stdexec

ARG NVIDIA_STDEXEC_REF

RUN <<EOF

    set -ex

    git clone --branch main --shallow-since=2024-06-01 https://github.com/NVIDIA/stdexec /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}

    cd /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}

    git checkout ${NVIDIA_STDEXEC_REF}
EOF

# Build the final image from previous stages.
FROM requirements AS final

ARG DOXYGEN_VERSION
ARG GOOGLETEST_VERSION
ARG HPX_REF
ARG KOKKOS_VERSION
ARG KOKKOS_PRESET
ARG NVIDIA_STDEXEC_REF

COPY --from=doxygen-compile     /opt/doxygen-${DOXYGEN_VERSION}                /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-test-compile /opt/google-test-${GOOGLETEST_VERSION}         /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=hpx-compile         /opt/hpx-${HPX_REF}                            /opt/hpx-${HPX_REF}
COPY --from=kokkos-compile      /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET} /opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}
COPY --from=nvidia-stdexec      /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}      /opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}

ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV HPX_ROOT=/opt/hpx-${HPX_REF}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_VERSION}/${KOKKOS_PRESET}
ENV Stdexec_ROOT=/opt/nvidia/stdexec-${NVIDIA_STDEXEC_REF}
