FROM ghcr.io/uliegecsm/graph-dispatching/graph-dispatching:clang-22-HPX

# Install gpg and gnupg2 allows the container to use GPG keys to sign commits.
# See also:
#   - https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
RUN apt-helpers install-packages --update --clean --packages gpg gnupg2
