name: Build and test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io

jobs:

    set-vars:
        runs-on: [self-hosted, linux, docker, amd64]
        outputs:
            CI_IMAGE : ${{ steps.common.outputs.CI_IMAGE }}
        steps:
            - name: Export common variables.
              id  : common
              run : |
                  echo "CI_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/graph-dispatching" >> $GITHUB_OUTPUT

    build-images:
        needs: [set-vars]
        runs-on: ${{ fromJSON(matrix.runs-on || '["ubuntu-latest"]') }}
        container:
            image: ${{ matrix.builder || 'docker:latest' }}
        permissions:
            packages: write
            contents: read
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler_family: gcc
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64']"
                    - backend        : OpenMP
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64']"
                    - backend        : HPX
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64']"
                    - backend        : Cuda
                      compiler_family: gcc
                      base_image     : nvidia/cuda:12.6.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64']"
                    - backend        : HPX
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/arm64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'arm64']"
                      builder        : sarouman.meca.ulg.ac.be:5000/trilinos-container/builder:ubuntu22.04-latest-arm64
        steps:
            - uses: actions/checkout@v4

            - if : ${{ matrix.builder == '' }}
              run: apk add jq

            - uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: ./.github/actions/build-image
              with:
                  backend        : ${{ matrix.backend }}
                  base_image     : ${{ matrix.base_image }}
                  compiler_family: ${{ matrix.compiler_family }}
                  platforms      : ${{ matrix.platforms }}
                  tag            : ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler_family }}-${{ matrix.backend }}${{ runner.arch == 'ARM64' && '-arm64' || '' }}

    build-library-and-test:
        needs: [set-vars, build-images]
        runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler_family: gcc
                    - backend        : OpenMP
                      compiler_family: clang
                    - backend        : HPX
                      compiler_family: clang
                    - backend        : Cuda
                      compiler_family: gcc
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'volta70']"
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler_family }}-${{ matrix.backend }}
        steps:
            - uses: actions/checkout@v4

            - run : |
                  cmake -S .    --preset=${{ matrix.compiler_family }}-${{ matrix.backend }} --warn-uninitialized -Werror=dev
                  cmake --build --preset=${{ matrix.compiler_family }}-${{ matrix.backend }} -j$(nproc)

            - run : |
                  ctest --preset=${{ matrix.compiler_family }}-${{ matrix.backend }}

    build-documentation:
        needs: [set-vars, build-images]
        runs-on: [self-hosted, linux, docker, amd64]
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:gcc-OpenMP
        steps:
            - uses: actions/checkout@v4

            - run : |
                  cmake -S .    --preset=gcc-OpenMP --warn-uninitialized -Werror=dev
                  cmake --build --preset=gcc-OpenMP --target=docs
