name: Build and test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            build-images:
                description: 'Force re-build of all Docker images.'
                required: false
                type: bool
                default: false
    schedule:
        # At 06:00 on Sunday.
        - cron:  '0 6 * * 6'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
    contents: read
    packages: read

env:
    REGISTRY: ghcr.io
    # Enable ccache size larger than the default (5G).
    CCACHE_MAXSIZE: 15G

jobs:

    set-vars:
        runs-on: [self-hosted, linux, docker, amd64]
        outputs:
            CI_BUILDER: ${{ steps.common.outputs.CI_BUILDER }}
            CI_IMAGE  : ${{ steps.common.outputs.CI_IMAGE }}
        steps:
            - name: Export common variables.
              id  : common
              run : |
                  echo "CI_BUILDER=${{ env.REGISTRY }}/${{ github.repository }}/docker:builder" >> $GITHUB_OUTPUT
                  echo "CI_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/graph-dispatching" >> $GITHUB_OUTPUT

    setup-skips:
        runs-on: [self-hosted, linux, docker, amd64]
        container:
            image: alpine/git:2.49.1@sha256:26f8647ec43523c2511b99064cb45b48f4535bce956b9377a94b289fb021e819
        outputs:
            build-docker: ${{ steps.build-docker.outputs.build-docker }}
            build-images: ${{ steps.build-images.outputs.build-images }}
        permissions:
            contents: read
            pull-requests: read
        steps:
            - uses: actions/checkout@v6
            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - id: build-docker-changed-files
              uses: tj-actions/changed-files@v47
              with:
                  files: |
                      docker/dockerfile.builder

            - id: build-docker
              env:
                  ANY_CHANGED: ${{ steps.build-docker-changed-files.outputs.any_changed == 'true' }}
                  FORCE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['build-images'] }}
              run: |
                  if [ "$ANY_CHANGED" = "true" ] || [ "$FORCE" = "true" ]; then
                      BUILD_DOCKER=true
                  else
                      BUILD_DOCKER=false
                  fi
                  echo "BUILD_DOCKER set to ${BUILD_DOCKER} because:"
                  echo "    - any changed: ${ANY_CHANGED}"
                  echo "    - force      : ${FORCE}"
                  echo "build-docker=${BUILD_DOCKER}" >> $GITHUB_OUTPUT

            - id: build-images-changed-files
              uses: tj-actions/changed-files@v47
              with:
                  files: |
                      .github/**
                      cmake/presets/**
                      docker/**
                      requirements/**
                      version.json

            - id: build-images
              env:
                  ANY_CHANGED: ${{ steps.build-images-changed-files.outputs.any_changed == 'true' }}
                  FORCE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['build-images'] }}
              run: |
                  if [ "$ANY_CHANGED" = "true" ] || [ "$FORCE" = "true" ]; then
                      BUILD_IMAGES=true
                  else
                      BUILD_IMAGES=false
                  fi
                  echo "BUILD_IMAGES set to ${BUILD_IMAGES} because:"
                  echo "    - any changed: ${ANY_CHANGED}"
                  echo "    - force      : ${FORCE}"
                  echo "build-images=${BUILD_IMAGES}" >> $GITHUB_OUTPUT

    build-docker:
        needs: [set-vars, setup-skips]
        if: ${{ ! failure() && ! cancelled() && needs.setup-skips.outputs.build-docker == 'true' }}
        runs-on: [self-hosted, linux, docker, amd64]
        container:
            image: docker:latest
        permissions:
            contents: read
            packages: write
            pull-requests: read
        steps:
            # This should only sparsely checkout 'docker/dockerfile.docker', but we're hitting
            # the issue https://github.com/actions/checkout/issues/1992.
            - uses: actions/checkout@v6
              with:
                  set-safe-directory: true

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - uses: docker/login-action@v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/setup-buildx-action@v4

            - uses: docker/build-push-action@v7.2.0
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: ${{ github.ref == 'refs/heads/main' }}
                  file: docker/dockerfile.builder
                  tags: ${{ needs.set-vars.outputs.CI_BUILDER }}
                  cache-from: type=registry,ref=${{ needs.set-vars.outputs.CI_BUILDER }}
                  cache-to: type=inline
                  build-args: |
                      BASE_IMAGE=ubuntu:24.04
                  labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"

    build-images:
        needs: [set-vars, setup-skips, build-docker]
        if: ${{ ! failure() && ! cancelled() && needs.setup-skips.outputs.build-images == 'true' }}
        runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
        container:
            image: ${{ needs.set-vars.outputs.CI_BUILDER }}
        permissions:
            contents: read
            packages: write
            pull-requests: read
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler       : {family: gnu, version: 14}
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : OpenMP
                      compiler       : {family: clang, version: 22}
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : HPX
                      compiler       : {family: clang, version: 22}
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : Cuda
                      compiler       : {family: gnu, version: 14}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [VOLTA70]
                    - backend        : HIP
                      compiler       : {family: rocm, version: 6.4}
                      base_image     : rocm/dev-ubuntu-24.04:6.4
                      platforms      : linux/amd64
                      kokkos_archs   : [AMD_GFX906]
                    - backend        : HPX
                      compiler       : {family: clang, version: 22}
                      base_image     : ubuntu:24.04
                      platforms      : linux/arm64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'arm64']"
                    - backend        : Cuda
                      compiler       : {family: clang, version: 22}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [BLACKWELL120]
                    - backend        : Cuda
                      compiler       : {family: gnu, version: 14}
                      base_image     : nvcr.io/nvidia/cuda:13.3.0-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [BLACKWELL120]
                    - backend        : HPX-Cuda
                      compiler       : {family: clang, version: 22}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [VOLTA70]
                    - backend        : Cuda
                      compiler       : {family: clang, version: 22}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [AMPERE80]
                    - backend        : Cuda
                      compiler       : {family: clang, version: 22}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [ZEN3, AMPERE86]
                    - backend        : Cuda
                      compiler       : {family: gnu, version: 14}
                      base_image     : nvcr.io/nvidia/cuda:13.0.0-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [AMPERE86]
                    - backend        : HIP
                      compiler       : {family: rocm, version: 7.2.4}
                      base_image     : rocm/dev-ubuntu-24.04:7.2.4
                      platforms      : linux/amd64
                      kokkos_archs   : [ZEN5, AMD_GFX1201]
                    - backend        : HIP
                      compiler       : {family: rocm, version: 7.2.4}
                      base_image     : rocm/dev-ubuntu-24.04:7.2.4
                      platforms      : linux/amd64
                      kokkos_archs   : [SPR, AMD_GFX942]
                    - backend        : SYCL
                      compiler       : {family: intel, version: 2025.3}
                      base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [VOLTA70]
        steps:
            - uses: actions/checkout@v6
              with:
                   set-safe-directory: true

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - uses: docker/login-action@v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Compute the image tag suffix.
              id  : compute-tag-suffix
              run : |
                  # We don't use multi-platform build for ARM64 because it's too slow. Instead, we use a native
                  # runner and append '-arm64' to the image tag.
                  TAG_SUFFIX=${{ matrix.kokkos_archs && '-' || '' }}${{ join(matrix.kokkos_archs, '-')}}${{ runner.arch == 'ARM64' && '-arm64' || '' }}
                  TAG_SUFFIX=$(echo ${TAG_SUFFIX} | tr '[:upper:]' '[:lower:]')
                  echo "Computed image tag suffix: ${TAG_SUFFIX}."
                  echo "TAG_SUFFIX=${TAG_SUFFIX}" >> $GITHUB_OUTPUT

            - uses: ./.github/actions/build-image
              with:
                  backend        : ${{ matrix.backend }}
                  base_image     : ${{ matrix.base_image }}
                  compiler       : ${{ toJSON(matrix.compiler) }}
                  kokkos_archs   : ${{ toJSON(matrix.kokkos_archs) }}
                  platforms      : ${{ matrix.platforms }}
                  tag            : ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler.family }}-${{ matrix.compiler.version }}-${{ matrix.backend }}${{ steps.compute-tag-suffix.outputs.TAG_SUFFIX }}

    clang-format:
        needs: [set-vars, build-images]
        runs-on: [self-hosted, linux, docker, amd64]
        if: ${{ ! failure() && ! cancelled() }}
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:clang-OpenMP
        steps:
            - uses: actions/checkout@v6
            - run: bash clang-format.sh

    build-library-and-test:
        needs: [set-vars, build-images]
        runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
        if: ${{ ! failure() && ! cancelled() }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler       : {family: gnu, version: 14}
                    - backend        : OpenMP
                      compiler       : {family: clang, version: 22}
                    - backend        : HPX
                      compiler       : {family: clang, version: 22}
                    - backend        : Cuda
                      compiler       : {family: gnu, version: 14}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'volta70', 'gpu:0']"
                      tag_suffix     : -volta70
                    - backend        : Cuda
                      compiler       : {family: clang, version: 22}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'blackwell120', 'gpu:0', 'gpu:1']"
                      tag_suffix     : -blackwell120
                    - backend        : Cuda
                      compiler       : {family: gnu, version: 14}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'blackwell120', 'gpu:0', 'gpu:1']"
                      tag_suffix     : -blackwell120
                    - backend        : HPX-Cuda
                      compiler       : {family: clang, version: 22}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'volta70', 'gpu:0']"
                      tag_suffix     : -volta70
                    - backend        : HIP
                      compiler       : {family: rocm, version: 6.4}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'amd_gfx906', 'gpu:0', 'gpu:1']"
                      docker_run_args: --privileged
                      tag_suffix     : -amd_gfx906
                    - backend        : HIP
                      compiler       : {family: rocm, version: 7.2.4}
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'amd_gfx1201', 'gpu:0']"
                      docker_run_args: --privileged
                      tag_suffix     : -zen5-amd_gfx1201
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler.family }}-${{ matrix.compiler.version }}-${{ matrix.backend }}${{ matrix.tag_suffix }}
            # The 'options' field cannot be empty. Provide '--annotation' to ensure that if 'docker_run_args' is empty, the workflow is still valid.
            options: "--annotation ref=${{ github.ref }} ${{ matrix.docker_run_args }}"
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: Show ccache statistics.
              run : |
                  ccache --verbose --show-stats
                  ccache --verbose --show-compression

            - name: Detect multi-GPU from the labels.
              run : |
                  python3 .github/workflows/test-environment.py \
                      --runs-on="${{matrix.runs-on }}" \
                      --output=$GITHUB_ENV

            - run : |
                  cmake -S .    --preset=${{ matrix.compiler.family }}-${{ matrix.backend }}
                  cmake --build --preset=${{ matrix.compiler.family }}-${{ matrix.backend }} -j$(nproc)

            - run : |
                  python3 tests/check_tests.py --preset=${{ matrix.compiler.family }}-${{ matrix.backend }}

            - run : |
                  ctest --preset=${{ matrix.compiler.family }}-${{ matrix.backend }}

    build-documentation:
        needs: [set-vars, build-images]
        runs-on: [self-hosted, linux, docker, amd64]
        if: ${{ ! failure() && ! cancelled() }}
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:gnu-14-OpenMP
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - run : |
                  cmake -S .    --preset=gnu-OpenMP -DENABLE_DOXYGEN:BOOL=ON
                  cmake --build --preset=gnu-OpenMP --target=docs
