name: Build and test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    schedule:
        # At 06:00 on Sunday.
        - cron:  '0 6 * * 6'

env:
    REGISTRY: ghcr.io
    # Enable ccache size larger than the default (5G).
    CCACHE_MAXSIZE: 15G

jobs:

    set-vars:
        runs-on: [self-hosted, linux, docker, amd64]
        outputs:
            CI_BUILDER: ${{ steps.common.outputs.CI_BUILDER }}
            CI_IMAGE  : ${{ steps.common.outputs.CI_IMAGE }}
        steps:
            - name: Export common variables.
              id  : common
              run : |
                  echo "CI_BUILDER=${{ env.REGISTRY }}/${{ github.repository }}/docker:builder" >> $GITHUB_OUTPUT
                  echo "CI_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/graph-dispatching" >> $GITHUB_OUTPUT

    build-docker:
        needs: [set-vars]
        runs-on: [self-hosted, linux, docker, amd64]
        container:
            image: docker:latest
        permissions:
            contents: read
            packages: write
            pull-requests: read
        steps:
            # This should only sparsely checkout 'docker/dockerfile.docker', but we're hitting
            # the issue https://github.com/actions/checkout/issues/1992.
            - uses: actions/checkout@v4
              with:
                  set-safe-directory: true

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - id: changed-files
              uses: tj-actions/changed-files@v45
              with:
                  files: docker/dockerfile.builder

            - uses: docker/login-action@v3
              if  : steps.changed-files.outputs.any_changed == 'true'
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/setup-buildx-action@v3
              if  : steps.changed-files.outputs.any_changed == 'true'

            - uses: docker/build-push-action@v6.13.0
              if  : steps.changed-files.outputs.any_changed == 'true'
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: ${{ github.ref == 'refs/heads/main' }}
                  file: docker/dockerfile.builder
                  tags: ${{ needs.set-vars.outputs.CI_BUILDER }}
                  cache-from: type=registry,ref=${{ needs.set-vars.outputs.CI_BUILDER }}
                  cache-to: type=inline
                  build-args: |
                      BASE_IMAGE=ubuntu:24.04
                  labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"

    build-images:
        needs: [set-vars, build-docker]
        runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
        container:
            image: ${{ needs.set-vars.outputs.CI_BUILDER }}
        permissions:
            contents: read
            packages: write
            pull-requests: read
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler_family: gcc
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : OpenMP
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : HPX
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/amd64
                    - backend        : Cuda
                      compiler_family: gcc
                      base_image     : nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [VOLTA70]
                    - backend        : HIP
                      compiler_family: rocm
                      base_image     : rocm/dev-ubuntu-24.04:6.4
                      platforms      : linux/amd64
                      kokkos_archs   : [AMD_GFX906]
                    - backend        : HPX
                      compiler_family: clang
                      base_image     : ubuntu:24.04
                      platforms      : linux/arm64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'arm64']"
                    - backend        : Cuda
                      compiler_family: clang
                      base_image     : nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [BLACKWELL120]
                    - backend        : HPX-Cuda
                      compiler_family: clang
                      base_image     : nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [VOLTA70]
                    - backend        : Cuda
                      compiler_family: clang
                      base_image     : nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/amd64
                      kokkos_archs   : [AMPERE80]
                    - backend        : Cuda
                      compiler_family: gcc
                      base_image     : nvidia/cuda:12.8.1-devel-ubuntu24.04
                      platforms      : linux/arm64
                      runs-on        : "['self-hosted', 'linux', 'docker', 'arm64']"
                      kokkos_archs   : [ARMV9_GRACE, HOPPER90]
                    - backend        : HIP
                      compiler_family: rocm
                      base_image     : rocm/dev-ubuntu-24.04:6.4
                      platforms      : linux/amd64
                      kokkos_archs   : [ZEN4, AMD_GX942_APU]
        steps:
            - uses: actions/checkout@v4
              with:
                   set-safe-directory: true

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - id: changed-files
              uses: tj-actions/changed-files@v45
              with:
                  files: |
                      .github/**
                      cmake/presets/**
                      docker/**
                      requirements/**
                      version.json

            - uses: docker/login-action@v3
              if  : steps.changed-files.outputs.any_changed == 'true'
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Compute the image tag suffix.
              id  : compute-tag-suffix
              run : |
                  # We don't use multi-platform build for ARM64 because it's too slow. Instead, we use a native
                  # runner and append '-arm64' to the image tag.
                  TAG_SUFFIX=${{ matrix.kokkos_archs && '-' || '' }}${{ join(matrix.kokkos_archs, '-')}}${{ runner.arch == 'ARM64' && '-arm64' || '' }}
                  TAG_SUFFIX=$(echo ${TAG_SUFFIX} | tr '[:upper:]' '[:lower:]')
                  echo "Computed image tag suffix: ${TAG_SUFFIX}."
                  echo "TAG_SUFFIX=${TAG_SUFFIX}" >> $GITHUB_OUTPUT

            - uses: ./.github/actions/build-image
              if  : steps.changed-files.outputs.any_changed == 'true'
              with:
                  backend        : ${{ matrix.backend }}
                  base_image     : ${{ matrix.base_image }}
                  compiler_family: ${{ matrix.compiler_family }}
                  kokkos_archs   : ${{ toJSON(matrix.kokkos_archs) }}
                  platforms      : ${{ matrix.platforms }}
                  tag            : ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler_family }}-${{ matrix.backend }}${{ steps.compute-tag-suffix.outputs.TAG_SUFFIX }}

    build-library-and-test:
        needs: [set-vars, build-images]
        runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - backend        : OpenMP
                      compiler_family: gcc
                    - backend        : OpenMP
                      compiler_family: clang
                    - backend        : HPX
                      compiler_family: clang
                    - backend        : Cuda
                      compiler_family: gcc
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'volta70', 'gpu:0']"
                      tag_suffix     : -volta70
                    - backend        : Cuda
                      compiler_family: clang
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'blackwell120', 'gpu:0', 'gpu:1']"
                      tag_suffix     : -blackwell120
                    - backend        : HPX-Cuda
                      compiler_family: clang
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'volta70', 'gpu:0']"
                      tag_suffix     : -volta70
                    - backend        : HIP
                      compiler_family: rocm
                      runs-on        : "['self-hosted', 'linux', 'docker', 'amd64', 'amd_gfx906', 'gpu:0', 'gpu:1']"
                      docker_run_args: --privileged
                      tag_suffix     : -amd_gfx906
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler_family }}-${{ matrix.backend }}${{ matrix.tag_suffix }}
            # The 'options' field cannot be empty. Provide '--annotation' to ensure that if 'docker_run_args' is empty, the workflow is still valid.
            options: "--annotation ref=${{ github.ref }} ${{ matrix.docker_run_args }}"
        steps:
            - uses: actions/checkout@v4

            - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: Show ccache statistics.
              run : |
                  ccache --verbose --show-stats
                  ccache --verbose --show-compression

            - name: Detect multi-GPU from the labels.
              run : |
                  python3 .github/workflows/test-environment.py \
                      --runs-on="${{matrix.runs-on }}" \
                      --output=$GITHUB_ENV

            - run : |
                  cmake -S .    --preset=${{ matrix.compiler_family }}-${{ matrix.backend }}
                  cmake --build --preset=${{ matrix.compiler_family }}-${{ matrix.backend }} -j$(nproc)

            - run : |
                  python3 tests/check_tests.py --preset=${{ matrix.compiler_family }}-${{ matrix.backend }}

            - run : |
                  ctest --preset=${{ matrix.compiler_family }}-${{ matrix.backend }}

    build-documentation:
        needs: [set-vars, build-images]
        runs-on: [self-hosted, linux, docker, amd64]
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}:gcc-OpenMP
        steps:
            - uses: actions/checkout@v4

            - run : |
                  cmake -S .    --preset=gcc-OpenMP -DENABLE_DOXYGEN:BOOL=ON
                  cmake --build --preset=gcc-OpenMP --target=docs
